### PR TITLE
LPS-162895

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123666

**Comment by ces-sontruong** [comment]
Hi @brianchandotcom,

The fix works well but the test failed on my end. Expected 4 emails are sent which was declared at:
```
String to = "ava@gmail.com, bryn@gmail.com;caleb@gmail.com\ndavid@gmail.com";
```
Could you double-check?
Thanks!

**Comment by brianchandotcom** [comment]
@sontruongces I did that on purpose. I want you to see what I was doing and do the rest for me.

I want to test abc@def.hij.com etc.

**Comment by ces-sontruong** [comment]
@brianchandotcom Sure, I will update the test with that case. But I have a little bit confused about this commit:  https://github.com/sontruongces/liferay-portal/pull/41/commits/53051dee5e85c15f46f604352d9822e47a05d6d8
Could you more detail about it?

**Comment by ces-sontruong** [comment]
Resent at brianchandotcom#123928

**Pull request closed without merging**
